import type { VendorId } from "../vendors/table";
import type { Maker } from "./types";

// Every word is matched on word boundaries (a digit or hyphen may follow, a
// letter may not), so "meta" never hits "metadata" and "o3" still hits "o3-mini".
// "google" is a cloud host, not a maker word for anyone else's foreign list.
//
// Model globs run over the normalised id (lowercase, `.` and `_` to `-`, any
// `vendor/` prefix stripped). Relays and marketplaces prefix and suffix freely
// (`coding-glm-5-3-free`, `e2ee-qwen3-6-35b-a3b`, `morph-kimik3`,
// `xiaomi-mimo-v2-5`), so a family word is matched anywhere in the id when it
// cannot collide with another family, and anchored when it can.
export const MAKERS = [
  {
    id: "anthropic",
    name: "Anthropic",
    wire: "anthropic",
    models: ["*claude*", "kiro*"],
    home: ["anthropic"],
    modelNames: ["claude", "anthropic"],
    cloudModelNames: ["amazon q", "q developer", "kiro"],
    acceptsCloudHost: true,
    // `fable` is load-bearing: without it tierOf() returns null for
    // claude-fable-5 and a relay serving opus under a fable label is never checked.
    tiers: ["opus", "sonnet", "haiku", "fable"],
    cjkNative: false,
  },
  {
    id: "openai",
    name: "OpenAI",
    wire: "openai",
    models: [
      "gpt-*",
      "*-gpt-*",
      "chatgpt*",
      "o1*",
      "o3*",
      "o4*",
      "codex*",
      "*-codex*",
      "deep-research*",
    ],
    home: ["openai"],
    modelNames: ["gpt", "chatgpt", "openai", "o1", "o3", "o4", "codex"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "google",
    name: "Google",
    wire: "gemini",
    models: ["*gemini*", "*gemma*", "antigravity*", "*nano-banana*"],
    home: ["google", "deepmind"],
    modelNames: ["gemini", "google", "gemma"],
    acceptsCloudHost: false,
    // Marketplaces sell flash under a pro label; the reply's model field and
    // the self-report both name the tier.
    tiers: ["pro", "flash"],
    cjkNative: false,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    wire: "openai",
    models: ["*deepseek*", "*dsv3*", "*dsv4*", "*dsv5*"],
    home: ["deepseek", "deepseek-ai", "深度求索"],
    modelNames: ["deepseek"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
    // Measured on Cloudflare's own deepseek route as well as on every
    // marketplace: V4 answers "openai", "chatgpt" or "gpt-4o" about half the
    // time and "anthropic" now and then. Its training data, not a swap.
    selfConfusions: ["openai", "gpt", "chatgpt", "anthropic", "claude"],
  },
  {
    id: "moonshot",
    name: "Moonshot AI",
    wire: "openai",
    models: ["*kimi*", "moonshot*"],
    home: ["moonshot", "moonshotai", "月之暗面"],
    modelNames: ["kimi"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "zhipu",
    name: "Zhipu AI",
    wire: "openai",
    models: ["*glm*"],
    home: ["zhipu", "zhipuai", "z.ai", "智谱"],
    modelNames: ["glm", "chatglm"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "minimax",
    name: "MiniMax",
    wire: "openai",
    models: ["*minimax*", "abab*"],
    home: ["minimax", "minimaxai", "稀宇"],
    modelNames: ["minimax", "abab"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "xiaomi",
    name: "Xiaomi",
    wire: "openai",
    models: ["*mimo*"],
    home: ["xiaomi", "小米"],
    modelNames: ["mimo"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "mistral",
    name: "Mistral AI",
    wire: "openai",
    models: [
      "*mistral*",
      "*mixtral*",
      "*codestral*",
      "*magistral*",
      "*devstral*",
      "*ministral*",
      "*pixtral*",
      "*leanstral*",
    ],
    home: ["mistral", "mistralai"],
    modelNames: [
      "mistral",
      "mixtral",
      "codestral",
      "magistral",
      "devstral",
      "ministral",
      "pixtral",
      "leanstral",
    ],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "alibaba",
    name: "Alibaba",
    wire: "openai",
    models: ["*qwen*", "*qwq*", "*qvq*"],
    home: ["alibaba", "qwen", "tongyi", "阿里", "通义"],
    modelNames: ["qwen", "qwq", "qvq"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "meta",
    name: "Meta",
    wire: "openai",
    // l3-*, l31-* and l3-3-* are the community finetunes of Llama 3.
    models: ["*llama*", "l3-*", "l31-*", "*muse-spark*", "*muse-glimmer*"],
    home: ["meta", "facebook"],
    modelNames: ["llama", "muse"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "xai",
    name: "xAI",
    wire: "openai",
    models: ["*grok*"],
    home: ["xai", "x.ai"],
    modelNames: ["grok"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "writer",
    name: "Writer",
    wire: "openai",
    models: ["*palmyra*"],
    // "writer" is ordinary English and would land in every other maker's
    // foreign list; the model name is the tell.
    home: [],
    modelNames: ["palmyra"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "tencent",
    name: "Tencent",
    wire: "openai",
    // No `hy*` glob: it would claim hybrid-* and hyper-* ids.
    models: ["*hunyuan*", "hy3*", "hy4*", "hy-*"],
    home: ["tencent", "hunyuan", "腾讯", "混元"],
    modelNames: ["hunyuan", "hy"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "cohere",
    name: "Cohere",
    wire: "openai",
    models: [
      "command*",
      "*-command-*",
      "c4ai*",
      "aya-*",
      "*-aya-*",
      "tiny-aya*",
      "north-*",
    ],
    home: ["cohere", "cohere labs", "coherelabs"],
    modelNames: ["command", "aya", "c4ai"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "bytedance",
    name: "ByteDance",
    wire: "openai",
    models: ["*doubao*", "seed-*", "*-seed-*", "seedream*", "seedance*"],
    home: ["bytedance", "volcengine", "字节跳动", "火山引擎"],
    modelNames: ["doubao", "seed"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "baidu",
    name: "Baidu",
    wire: "openai",
    models: ["*ernie*"],
    home: ["baidu", "百度"],
    modelNames: ["ernie"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "stepfun",
    name: "StepFun",
    wire: "openai",
    models: ["step-*", "*-step-*"],
    home: ["stepfun", "阶跃星辰"],
    // "step" alone is ordinary English; the versioned name is the tell.
    modelNames: ["stepfun"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    wire: "openai",
    models: ["*nemotron*", "*riva-*"],
    home: ["nvidia"],
    modelNames: ["nemotron"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "ibm",
    name: "IBM",
    wire: "openai",
    models: ["*granite*"],
    home: ["ibm"],
    modelNames: ["granite"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "liquid",
    name: "Liquid AI",
    wire: "openai",
    models: ["lfm*", "*-lfm-*"],
    home: ["liquid", "liquid ai"],
    modelNames: ["lfm"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "kwaipilot",
    name: "Kwaipilot",
    wire: "openai",
    models: ["*kat-coder*"],
    home: ["kwaipilot", "kuaishou", "快手"],
    modelNames: ["kat-coder"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "meituan",
    name: "Meituan",
    wire: "openai",
    models: ["*longcat*"],
    home: ["meituan", "美团"],
    modelNames: ["longcat"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "inclusionai",
    name: "inclusionAI",
    wire: "openai",
    models: ["ling-*", "*-ling-*", "ring-*", "*-ring-*"],
    home: ["inclusionai", "ant group", "蚂蚁"],
    modelNames: ["inclusionai"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "internlm",
    name: "Shanghai AI Lab",
    wire: "openai",
    models: ["intern*", "*-intern-*"],
    home: ["shanghai ai lab", "internlm", "上海人工智能实验室", "书生"],
    modelNames: ["internlm", "internvl", "intern-s"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "openbmb",
    name: "OpenBMB",
    wire: "openai",
    models: ["*minicpm*"],
    home: ["openbmb", "modelbest", "面壁"],
    modelNames: ["minicpm"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "sensetime",
    name: "SenseTime",
    wire: "openai",
    models: ["*sensenova*", "*sensechat*"],
    home: ["sensetime", "商汤"],
    modelNames: ["sensenova", "sensechat"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "rednote",
    name: "rednote",
    wire: "openai",
    models: ["dots*", "*-dots-*"],
    home: ["rednote", "xiaohongshu", "小红书"],
    modelNames: ["dots"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: true,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    wire: "openai",
    models: ["sonar*", "*-sonar-*"],
    home: ["perplexity"],
    modelNames: ["sonar"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "microsoft",
    name: "Microsoft",
    wire: "openai",
    models: ["phi-*", "phi3*", "phi4*", "phi5*", "*-phi-*"],
    home: ["microsoft"],
    modelNames: ["phi"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "amazon",
    name: "Amazon",
    wire: "openai",
    models: ["nova-*", "*-nova-*"],
    home: ["amazon", "aws"],
    modelNames: ["nova"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    wire: "openai",
    models: ["*jamba*"],
    home: ["ai21"],
    modelNames: ["jamba"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "nous",
    name: "Nous Research",
    wire: "openai",
    models: ["hermes*", "*-hermes-*"],
    home: ["nous", "nous research"],
    modelNames: ["hermes"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "poolside",
    name: "Poolside",
    wire: "openai",
    models: ["laguna*", "*-laguna-*"],
    home: ["poolside"],
    modelNames: ["laguna"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "swissai",
    name: "Swiss AI",
    wire: "openai",
    models: ["*apertus*"],
    home: ["swiss ai", "swiss-ai", "eth zurich", "epfl"],
    modelNames: ["apertus"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "inception",
    name: "Inception Labs",
    wire: "openai",
    models: ["mercury*"],
    home: ["inception", "inception labs"],
    modelNames: ["mercury"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "arcee",
    name: "Arcee AI",
    wire: "openai",
    models: ["trinity*", "*-trinity-*", "*arcee*"],
    home: ["arcee"],
    modelNames: ["trinity"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "nexagi",
    name: "Nex AGI",
    wire: "openai",
    models: ["nex-*", "*-nex-*"],
    home: ["nex", "nex agi", "nex-agi"],
    modelNames: ["nex-n"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "sarvam",
    name: "Sarvam AI",
    wire: "openai",
    models: ["sarvam*"],
    home: ["sarvam"],
    modelNames: ["sarvam"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "typhoon",
    name: "SCB 10X",
    wire: "openai",
    models: ["typhoon*"],
    home: ["scb 10x", "scb10x", "typhoon"],
    modelNames: ["typhoon"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "moondream",
    name: "Moondream",
    wire: "openai",
    models: ["moondream*"],
    home: ["moondream", "m87"],
    modelNames: ["moondream"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "jetbrains",
    name: "JetBrains",
    wire: "openai",
    models: ["mellum*"],
    home: ["jetbrains"],
    modelNames: ["mellum"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "aion",
    name: "Aion Labs",
    wire: "openai",
    models: ["aion-*", "*-aion-*"],
    home: ["aion labs", "aion-labs", "aionlabs"],
    modelNames: ["aion"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
  {
    id: "venice",
    name: "Venice",
    wire: "openai",
    // Venice's own finetunes; the media models under the same prefix are
    // never probed on a text ladder.
    models: ["venice-*"],
    home: ["venice"],
    modelNames: ["venice"],
    acceptsCloudHost: false,
    tiers: null,
    cjkNative: false,
  },
] as const satisfies readonly Maker[];

export type MakerId = (typeof MAKERS)[number]["id"];

// A native wire that names no adapter is a typo; fail the build, not the run.
void (MAKERS satisfies readonly { wire: VendorId }[]);

export function makerFor<M extends string>(
  makers: readonly Maker<M>[],
  id: string,
): Maker<M> | undefined {
  return makers.find((m) => m.id === id);
}
